Feature/bytter til javalin
navikt/pam-stihibi pull request #6
Opened 2024-10-30 13:56 UTC by havardnyboe

Skriver om til å bruke Javalin og fjerner Micronaut.

Skal være en én-til-én omskrivning, det er ikke endret på noen logikk i BigQueryService.
Det eneste nye som er lagt til er noen enkle tester av BigQueryService

2024-10-30 13:59 UTC, havardnyboe commented on src/main/kotlin/no/nav/arbeidsplassen/stihibi/AdTopicListener.kt
> +        )
Den tidligere kafka-lytteren hentet inn en batch med meldinger fra topicet, her henter den bare en og en

2024-10-30 15:30 UTC, havardnyboe commented on src/main/kotlin/no/nav/arbeidsplassen/stihibi/ApplicationContext.kt
> +    }
BigQueryService initialiseres med `lazy` fordi BigQuery overskrives i tester og lokal kjøring. Alt som avhenger av BigQueryService må derfor også initialiseres med `lazy`.

2024-10-31 09:41 UTC, greger-nl requested changes
Denne trengs å testes mer i dev før den kan merge-es til main. Slik det er i dev nå så har den stoppet å lese meldinger den 22. oktober. Vi undersøker saken.

2024-10-31 09:41 UTC, greger-nl commented on src/main/kotlin/no/nav/arbeidsplassen/stihibi/KafkaExceptionHandler.kt
Er denne logikken ivaretatt noe annet sted nå?

2024-10-31 09:41 UTC, greger-nl commented on src/main/kotlin/no/nav/arbeidsplassen/stihibi/AdTopicListener.kt
> +        )
Ok, dette tror jeg vi skal ta en ekstra runde på. Ønsker egentlig å ha samme oppførsel som før, og det er vanlig å hente inn meldinger fra Kafka i batch-er.

2024-12-03 11:16 UTC, closed without merging